markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

docs_dir: sweep_framework/documentation

site_name: Sweep Framework Documentation
nav:
  - Overview: overview.md
  - Preparing Input Data: preparing_input_data.md
  - Features: features.md
  - Technical Documentation:
      - BaseDataset: classes/base_dataset.md
      - PlanDataset: classes/plan_dataset.md
      - FocalLoss: classes/focal_loss.md
      - LossStrategy: classes/loss_strategy.md
      - MetricSet: classes/metric_set.md
      - BaseConfig: classes/base_config.md
      - PlanModelConfig: classes/plan_config.md
      - SSTConfig: classes/sst_config.md
      - ModelRun: classes/model_run.md
      - ReportBuilder: classes/report_builder.md
      - SweepAnalyzer: classes/sweep_analyzer.md
      - SweepConfig: classes/sweep_config.md
      - SweepRegistry: classes/sweep_registry.md
      - Sweep: classes/sweep.md
  - Usage:
      - Unified Example: usage/unified_example.md
theme:
  name: material
